<a href="https://colab.research.google.com/github/pankajroy97/TestBook-Skill-Academy/blob/main/Assignment_MachineLearning%5BMajor%5D_by_Pankaj_Roy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###About Dataset
The dataset was developed by starting with satellite images of the ocean, some of which contain an oil spill and some that do not.
Images were split into sections and processed using computer vision algorithms to provide a vector of features to describe the contents of the image section or patch.

The task is, given a vector that describes the contents of a patch of a satellite image, then predicts whether the patch contains an oil spill or not, e.g. from the illegal or accidental dumping of oil in the ocean.

There are two classes and the goal is to distinguish between spill and non-spill using the features for a given ocean patch.

Non-Spill: negative case, or majority class.

Oil Spill: positive case, or minority class.

In [ ]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score,accuracy_score,r2_score
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import mean_absolute_error,mean_squared_error

###Download the OilSpill Dataset and perform Data cleaning and DataPre-Processing if Necessary.

In [ ]:
#Load our dataset
df=pd.read_csv('/content/oil_spill.csv')
df.head()

f_1    f_2      f_3     f_4  f_5       f_6    f_7   f_8      f_9  f_10  \
0    1   2558  1506.09  456.63   90   6395000  40.88  7.89  29780.0  0.19   
1    2  22325    79.11  841.03  180  55812500  51.11  1.21  61900.0  0.02   
2    3    115  1449.85  608.43   88    287500  40.42  7.34   3340.0  0.18   
3    4   1201  1562.53  295.65   66   3002500  42.40  7.97  18030.0  0.19   
4    5    312   950.27  440.86   37    780000  41.43  7.03   3350.0  0.17   

   ...     f_41      f_42     f_43     f_44   f_45  f_46      f_47   f_48  \
0  ...  2850.00   1000.00   763.16   135.46   3.73     0  33243.19  65.74   
1  ...  5750.00  11500.00  9593.48  1648.80   0.60     0  51572.04  65.73   
2  ...  1400.00    250.00   150.00    45.13   9.33     1  31692.84  65.81   
3  ...  6041.52    761.58   453.21   144.97  13.33     1  37696.21  65.67   
4  ...  1320.04    710.63   512.54   109.16   2.58     0  29038.17  65.66   

   f_49  target  
0  7.95       1  
1  6.26       0  
2  7.84       1  
3  8.07       1  
4  7.35       0  

[5 rows x 50 columns]

###Use the various methods such as Handling null values,One-HotEncoding,Imputation and Scaling of DataPre-Processing where necessary.

###Derive some insights from the dataset

In [ ]:
df.shape

(937, 50)

In [ ]:
df.columns

Index(['f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9', 'f_10',
       'f_11', 'f_12', 'f_13', 'f_14', 'f_15', 'f_16', 'f_17', 'f_18', 'f_19',
       'f_20', 'f_21', 'f_22', 'f_23', 'f_24', 'f_25', 'f_26', 'f_27', 'f_28',
       'f_29', 'f_30', 'f_31', 'f_32', 'f_33', 'f_34', 'f_35', 'f_36', 'f_37',
       'f_38', 'f_39', 'f_40', 'f_41', 'f_42', 'f_43', 'f_44', 'f_45', 'f_46',
       'f_47', 'f_48', 'f_49', 'target'],
      dtype='object')

In [ ]:
df.describe().T

count           mean           std       min        25%        50%  \
f_1     937.0      81.588047  6.497673e+01      1.00      31.00      64.00   
f_2     937.0     332.842049  1.931939e+03     10.00      20.00      65.00   
f_3     937.0     698.707086  5.999656e+02      1.92      85.27     704.37   
f_4     937.0     870.992209  5.227993e+02      1.00     444.20     761.28   
f_5     937.0      84.121665  4.536177e+01      0.00      54.00      73.00   
f_6     937.0  769696.378869  3.831151e+06  70312.00  125000.00  186300.00   
f_7     937.0      43.242721  1.271840e+01     21.24      33.65      39.97   
f_8     937.0       9.127887  3.588878e+00      0.83       6.75       8.20   
f_9     937.0    3940.712914  8.167428e+03    667.00    1371.00    2090.00   
f_10    937.0       0.221003  9.031555e-02      0.02       0.16       0.20   
f_11    937.0     109.892743  6.146085e+01     41.00      83.50      99.80   
f_12    937.0       0.251441  8.813206e-02      0.02       0.20       0.24   
f_13    937.0       0.311217  1.213863e-01      0.03       0.24       0.29   
f_14    937.0       0.484664  2.168587e-01      0.05       0.33       0.43   
f_15    937.0       0.182892  8.294307e-02      0.01       0.13       0.17   
f_16    937.0       0.301932  2.046949e-01      0.01       0.13       0.27   
f_17    937.0      77.412561  3.043298e+02      4.82      21.09      34.72   
f_18    937.0      31.151921  1.526933e+02      1.96      11.68      16.49   
f_19    937.0       0.909039  6.754919e-01      0.13       0.37       0.70   
f_20    937.0       0.228815  7.541045e-02      0.02       0.18       0.22   
f_21    937.0       0.289317  1.053665e-01      0.02       0.23       0.27   
f_22    937.0      76.085624  2.293747e+01     47.66      55.85      69.09   
f_23    937.0       0.000000  0.000000e+00      0.00       0.00       0.00   
f_24    937.0       0.642177  2.999451e-01      0.17       0.45       0.50   
f_25    937.0     559.910694  6.124593e+02    132.78     221.97     351.67   
f_26    937.0       0.578292  7.021573e-01     -0.71       0.18       0.87   
f_27    937.0       7.498196  3.967966e+00      2.96       4.66       5.07   
f_28    937.0       0.608399  8.452216e-01     -1.79       0.09       0.48   
f_29    937.0       4.271110  3.619406e+00      1.44       2.64       3.33   
f_30    937.0      -2.828420  1.621832e+00     -7.81      -3.25      -2.78   
f_31    937.0      -0.428869  2.156168e-01     -1.37      -0.53      -0.38   
f_32    937.0       1.824589  6.387222e-01      0.00       1.22       1.95   
f_33    937.0       0.002785  4.898794e-02      0.00       0.00       0.00   
f_34    937.0       1.821793  6.433976e-01      0.00       1.21       1.95   
f_35    937.0      43.086446  9.516733e+01      3.00      12.00      23.00   
f_36    937.0    2432.689434  5.219378e+03    360.00     720.00    1350.00   
f_37    937.0       0.006894  5.337192e-03      0.00       0.00       0.01   
f_38    937.0      31.241857  3.158484e+01      5.05      13.45      23.63   
f_39    937.0      91.189968  2.198441e+01     64.00      78.00      82.00   
f_40    937.0      60.547492  1.383890e+01     39.00      50.00      55.00   
f_41    937.0     933.928677  1.001681e+03      0.00     450.00     685.42   
f_42    937.0     427.565582  7.153916e+02      0.00     180.00     270.00   
f_43    937.0     255.435902  5.343062e+02      0.00      90.80     161.65   
f_44    937.0     106.112519  1.356177e+02      0.00      50.12      73.85   
f_45    937.0       5.014002  5.029151e+00      0.00       2.37       3.85   
f_46    937.0       0.128068  3.343443e-01      0.00       0.00       0.00   
f_47    937.0    7985.718004  6.854505e+03   2051.50    3760.57    5509.43   
f_48    937.0      61.694386  1.041281e+01     35.95      65.72      65.93   
f_49    937.0       8.119723  2.908895e+00      5.81       6.34       7.22   
target  937.0       0.043757  2.046625e-01      0.00       0.00       0.00   

              75%          ma

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937 entries, 0 to 936
Data columns (total 50 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   f_1     937 non-null    int64  
 1   f_2     937 non-null    int64  
 2   f_3     937 non-null    float64
 3   f_4     937 non-null    float64
 4   f_5     937 non-null    int64  
 5   f_6     937 non-null    int64  
 6   f_7     937 non-null    float64
 7   f_8     937 non-null    float64
 8   f_9     937 non-null    float64
 9   f_10    937 non-null    float64
 10  f_11    937 non-null    float64
 11  f_12    937 non-null    float64
 12  f_13    937 non-null    float64
 13  f_14    937 non-null    float64
 14  f_15    937 non-null    float64
 15  f_16    937 non-null    float64
 16  f_17    937 non-null    float64
 17  f_18    937 non-null    float64
 18  f_19    937 non-null    float64
 19  f_20    937 non-null    float64
 20  f_21    937 non-null    float64
 21  f_22    937 non-null    float64
 22  f_

###Data Preprocessing

Handle Null Values

In [ ]:
df.isnull().sum()

f_1       0
f_2       0
f_3       0
f_4       0
f_5       0
f_6       0
f_7       0
f_8       0
f_9       0
f_10      0
f_11      0
f_12      0
f_13      0
f_14      0
f_15      0
f_16      0
f_17      0
f_18      0
f_19      0
f_20      0
f_21      0
f_22      0
f_23      0
f_24      0
f_25      0
f_26      0
f_27      0
f_28      0
f_29      0
f_30      0
f_31      0
f_32      0
f_33      0
f_34      0
f_35      0
f_36      0
f_37      0
f_38      0
f_39      0
f_40      0
f_41      0
f_42      0
f_43      0
f_44      0
f_45      0
f_46      0
f_47      0
f_48      0
f_49      0
target    0
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
#Checking Datatypes
df.dtypes.value_counts()

float64    39
int64      11
dtype: int64

In [ ]:
#Checking the target column
df['target'].value_counts()

0    896
1     41
Name: target, dtype: int64

0 is majority ,so it is a Non-Spill.

1 is minority , so it is a oil spill.

Scaling of Data Pre-Processing

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
df_new=pd.DataFrame(mms.fit_transform(df),columns=df.columns)
df_new.head()

f_1       f_2       f_3       f_4       f_5       f_6       f_7  \
0  0.000000  0.078693  0.795369  0.167291  0.500000  0.088774  0.319870   
1  0.002849  0.689181  0.040816  0.308430  1.000000  0.782405  0.486482   
2  0.005698  0.003243  0.765631  0.223027  0.488889  0.003048  0.312378   
3  0.008547  0.036783  0.825213  0.108185  0.366667  0.041157  0.344625   
4  0.011396  0.009327  0.501465  0.161501  0.205556  0.009961  0.328827   

        f_8       f_9      f_10  ...      f_41      f_42      f_43      f_44  \
0  0.295893  0.181873  0.236111  ...  0.238507  0.086957  0.079550  0.077489   
1  0.015926  0.382532  0.000000  ...  0.481199  1.000000  1.000000  0.943179   
2  0.272842  0.016699  0.222222  ...  0.117161  0.021739  0.015636  0.025816   
3  0.299246  0.108469  0.236111  ...  0.505595  0.066224  0.047241  0.082929   
4  0.259849  0.016761  0.208333  ...  0.110470  0.061794  0.053426  0.062444   

       f_45  f_46      f_47      f_48      f_49  target  
0  0.048675   0.0  0.587669  0.976721  0.222222     1.0  
1  0.007830   0.0  0.932995  0.976393  0.046729     0.0  
2  0.121754   1.0  0.558460  0.979016  0.210800     1.0  
3  0.173953   1.0  0.671567  0.974426  0.234683     1.0  
4  0.033668   0.0  0.508444  0.974098  0.159917     0.0  

[5 rows x 50 columns]

###Apply various Machine Learning techniques to predict the output in target column,make use of Bagging and Ensemble as required and find the best model by evaluating the model using Model evaluation techniques.


In [ ]:
#Selecting dependent and independent features
x=df_new.drop('target',axis=1)
y=df_new['target']

In [ ]:
print(x.shape)
print(y.shape)

(937, 49)
(937,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2022)

###LOGISTIC REGRESSION

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(655, 49)
(282, 49)
(655,)
(282,)


In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model_train_lr=lr.fit(x_train,y_train)
y_train_predict=model_train_lr.predict(x_train)
print("Accuracy Score Trainning dataset",accuracy_score(y_train,y_train_predict)*100)

Accuracy Score Trainning dataset 95.72519083969465


In [ ]:
model_test_lr=lr.fit(x_test,y_test)
y_test_predict=model_test_lr.predict(x_test)
print("Accuracy Score Testing dataset",accuracy_score(y_test,y_test_predict)*100)

Accuracy Score Testing dataset 96.45390070921985


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_test_predict))
print(classification_report(y_test,y_test_predict))

[[272   0]
 [ 10   0]]
              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98       272
         1.0       0.00      0.00      0.00        10

    accuracy                           0.96       282
   macro avg       0.48      0.50      0.49       282
weighted avg       0.93      0.96      0.95       282



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
mae = mean_absolute_error(y_test,y_test_predict)
mse = mean_squared_error(y_test,y_test_predict)
rmse = np.sqrt(mse)
print(mae)
print(mse)
print(rmse)

0.03546099290780142
0.03546099290780142
0.18831089428867737


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
def eval_model(model,ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    acc=accuracy_score(ytest,ypred)
    print(cm)
    print('Accuracy Score',acc)
    print(classification_report(ytest,ypred))




def mscore(model):
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))


###Bagging Method

In [ ]:
#Importing the libraries for Model Building
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [ ]:
dtc=DecisionTreeClassifier(criterion='gini',max_depth=10,min_samples_split=20)

In [ ]:
x.shape[0]

937

In [ ]:
x.shape[1]

49

In [ ]:
bc_dtc=BaggingClassifier(base_estimator=dtc,n_estimators=15,max_samples=x.shape[0],max_features=x.shape[1],random_state=2022)
bc_dtc.fit(x,y)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=10,
                                                        min_samples_split=20),
                  max_features=49, max_samples=937, n_estimators=15,
                  random_state=2022)

In [ ]:
mscore(bc_dtc)

Training Score 0.9770992366412213
Testing Score 0.9787234042553191


In [ ]:
y_pred_bd=bc_dtc.predict(x_test)

In [ ]:
eval_model(bc_dtc,y_test,y_pred_bd)

[[272   0]
 [  6   4]]
Accuracy Score 0.9787234042553191
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       272
         1.0       1.00      0.40      0.57        10

    accuracy                           0.98       282
   macro avg       0.99      0.70      0.78       282
weighted avg       0.98      0.98      0.97       282



### AdaBoost method

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
tree = DecisionTreeClassifier(random_state=2022,max_depth=3,criterion='entropy',min_samples_split=8)

In [ ]:
ada_boost = AdaBoostClassifier(base_estimator=tree,n_estimators=80)
ada_boost.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                         max_depth=3,
                                                         min_samples_split=8,
                                                         random_state=2022),
                   n_estimators=80)

In [ ]:
mscore(ada_boost)

Training Score 1.0
Testing Score 0.9716312056737588


In [ ]:
y_pred_ab=ada_boost.predict(x_test)

In [ ]:
y_pred_ab

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
eval_model(ada_boost,y_test,y_pred_ab)

[[271   1]
 [  7   3]]
Accuracy Score 0.9716312056737588
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99       272
         1.0       0.75      0.30      0.43        10

    accuracy                           0.97       282
   macro avg       0.86      0.65      0.71       282
weighted avg       0.97      0.97      0.97       282



Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rand_for=RandomForestClassifier(n_estimators=80,criterion='gini',min_samples_split=20,max_depth=8)

In [ ]:
rand_for.fit(x_train,y_train)

RandomForestClassifier(max_depth=8, min_samples_split=20, n_estimators=80)

In [ ]:
mscore(rand_for)

Training Score 0.966412213740458
Testing Score 0.9645390070921985


In [ ]:
y_pred_rf=rand_for.predict(x_test)

In [ ]:
y_pred_rf

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
eval_model(rand_for,y_test,y_pred_rf)

[[271   1]
 [  9   1]]
Accuracy Score 0.9645390070921985
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98       272
         1.0       0.50      0.10      0.17        10

    accuracy                           0.96       282
   macro avg       0.73      0.55      0.57       282
weighted avg       0.95      0.96      0.95       282



###Save the best model and Load the model

In [ ]:
# Save the best model
import pickle

In [ ]:
pickle.dump(ada_boost,open('ada_boost.pkl','wb'))

In [ ]:
#load the model
loaded_model=pickle.load(open('ada_boost.pkl','rb'))
result=loaded_model.score(x_test,y_test)
result

0.9716312056737588

###Take the original dataset and make another dataset by randomly picking 20 datapoints from the oilspill dataset and apply the saved model on the same

In [ ]:
new_data=df_new[df_new['target']==0]
new_data=new_data.sample(n=20)

In [ ]:
new_data.shape

(20, 50)

In [ ]:
new_data.head()

f_1       f_2       f_3       f_4       f_5       f_6       f_7  \
574  0.014245  0.003552  0.009407  0.095566  0.500000  0.013225  0.419055   
802  0.196581  0.000618  0.013420  0.159618  0.011111  0.002424  0.600814   
748  0.042735  0.000371  0.015498  0.151188  0.344444  0.001514  0.464658   
733  0.000000  0.048303  0.005875  0.105472  0.472222  0.177965  0.664821   
1    0.002849  0.689181  0.040816  0.308430  1.000000  0.782405  0.486482   

          f_8       f_9      f_10  ...      f_41      f_42      f_43  \
574  0.520956  0.026319  0.361111  ...  0.112977  0.062609  0.059415   
802  0.474853  0.007903  0.263889  ...  0.067786  0.031304  0.018763   
748  0.321039  0.008234  0.208333  ...  0.087835  0.011068  0.002654   
733  0.698659  0.205369  0.361111  ...  0.673033  0.251533  0.179235   
1    0.015926  0.382532  0.000000  ...  0.481199  1.000000  1.000000   

         f_44      f_45  f_46      f_47      f_48      f_49  target  
574  0.069257  0.030928   0.0  0.184774  0.974754  0.047767     0.0  
802  0.051484  0.058724   0.0  0.000675  0.982623  0.032191     0.0  
748  0.030701  0.538040   1.0  0.004918  0.981639  0.035306     0.0  
733  0.430786  0.061073   0.0  0.035233  0.976066  0.042575     0.0  
1    0.943179  0.007830   0.0  0.932995  0.976393  0.046729     0.0  

[5 rows x 50 columns]

In [ ]:
random_data=new_data.drop('target',axis=1)

In [ ]:
random_data.head()

f_1       f_2       f_3       f_4       f_5       f_6       f_7  \
392  0.353276  0.001760  0.601197  0.367988  0.238889  0.001364  0.305049   
28   0.048433  0.001699  0.833970  0.365234  0.238889  0.001294  0.278502   
758  0.071225  0.000278  0.052946  0.137995  0.383333  0.001173  0.506189   
167  0.447293  0.001915  0.901166  0.482249  0.561111  0.001540  0.207980   
713  0.185185  0.000000  0.001364  0.103394  0.188889  0.000150  0.844625   

          f_8       f_9      f_10  ...      f_40      f_41      f_42  \
392  0.255239  0.004642  0.208333  ...  0.510638  0.041422  0.024595   
28   0.212070  0.010514  0.180556  ...  0.340426  0.097684  0.012297   
758  0.246857  0.006085  0.152778  ...  0.234043  0.067366  0.015652   
167  0.348701  0.011513  0.347222  ...  0.340426  0.073076  0.017927   
713  0.622800  0.000562  0.263889  ...  0.723404  0.027156  0.011068   

         f_43      f_44      f_45  f_46      f_47      f_48      f_49  
392  0.024219  0.038475  0.027796   0.0  0.048180  0.983607  0.161994  
28   0.006503  0.031599  0.244160   1.0  0.080018  0.986557  0.221184  
758  0.010554  0.018202  0.103745   0.0  0.008687  0.980984  0.062305  
167  0.014572  0.030421  0.081561   0.0  0.040139  0.992131  0.225337  
713  0.008845  0.042033  0.049850   0.0  0.255967  0.975738  0.040498  

[5 rows x 49 columns]

In [ ]:
random_data.to_csv('sample_submission_major_project.csv')

In [ ]:
sample=pd.read_csv('/content/sample_submission_major_project.csv')
sample.shape

(20, 50)

In [ ]:
sample.head()

Unnamed: 0       f_1       f_2       f_3       f_4       f_5       f_6  \
0         392  0.353276  0.001760  0.601197  0.367988  0.238889  0.001364   
1          28  0.048433  0.001699  0.833970  0.365234  0.238889  0.001294   
2         758  0.071225  0.000278  0.052946  0.137995  0.383333  0.001173   
3         167  0.447293  0.001915  0.901166  0.482249  0.561111  0.001540   
4         713  0.185185  0.000000  0.001364  0.103394  0.188889  0.000150   

        f_7       f_8       f_9  ...      f_40      f_41      f_42      f_43  \
0  0.305049  0.255239  0.004642  ...  0.510638  0.041422  0.024595  0.024219   
1  0.278502  0.212070  0.010514  ...  0.340426  0.097684  0.012297  0.006503   
2  0.506189  0.246857  0.006085  ...  0.234043  0.067366  0.015652  0.010554   
3  0.207980  0.348701  0.011513  ...  0.340426  0.073076  0.017927  0.014572   
4  0.844625  0.622800  0.000562  ...  0.723404  0.027156  0.011068  0.008845   

       f_44      f_45  f_46      f_47      f_48      f_49  
0  0.038475  0.027796   0.0  0.048180  0.983607  0.161994  
1  0.031599  0.244160   1.0  0.080018  0.986557  0.221184  
2  0.018202  0.103745   0.0  0.008687  0.980984  0.062305  
3  0.030421  0.081561   0.0  0.040139  0.992131  0.225337  
4  0.042033  0.049850   0.0  0.255967  0.975738  0.040498  

[5 rows x 50 columns]

In [ ]:
sample=sample.drop('Unnamed: 0',axis=1)

In [ ]:
loaded_model=pickle.load(open('ada_boost.pkl','rb'))
loaded_predicted_model=loaded_model.predict(sample)
loaded_predicted_model

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
#  Compare the actual data and predicted data
new_data["predicted_target"] =loaded_predicted_model

In [ ]:
print(new_data[['target','predicted_target']])

     target  predicted_target
574     0.0               0.0
802     0.0               0.0
748     0.0               0.0
733     0.0               0.0
1       0.0               0.0
201     0.0               0.0
916     0.0               0.0
158     0.0               0.0
188     0.0               0.0
184     0.0               0.0
409     0.0               0.0
502     0.0               0.0
41      0.0               0.0
578     0.0               0.0
641     0.0               0.0
52      0.0               0.0
685     0.0               0.0
735     0.0               0.0
154     0.0               0.0
17      0.0               0.0
